version: 2

sphinx:
  configuration: docs/source/conf.py  # adjust this path if your conf.py is elsewhere

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt
